### ISSUE TITLE
What configuration do you use for picorv32 core?

### ISSUE THREAD

**Issue by hyf6661669** [efabless/picorv32-soc-raven#1]
The core itself is configurable, and the author shows the consumed resources of different configurations in its document:
![image](https://user-images.githubusercontent.com/18757974/56216973-fbf3dc80-6094-11e9-8540-a88d19c1fd14.png)

Could you please tell me the configuration you use for the SoC?

**Comment by RTimothyEdwards** [comment]
Hello HYF,

> The core itself is configurable, and the author shows the consumed
> resources for 3 kinds of configurations in its document:
> image
> <https://user-images.githubusercontent.com/18757974/56216973-fbf3dc80-6094-11e9-8540-a88d19c1fd14.png>
>
> Could you please tell me the configuration you use for the SoC?

Without further investigation, I don't know what is meant by "small",
"medium", and "large" in the image.  It's not as helpful as a list of
parameters passed to the core module.  But I can say that for the
Raven chip I enabled most of the available options, such as the full
number of registers, IRQ, multiplier and divider, barrel shifter, etc.,
so I would guess that it is equivalent to "large".  On the other hand,
the image refers to an FPGA implementation and I don't know how to
directly compare the memory resources.  The Raven chip internalizes the
register bank as flops, but the SRAM is external to the SoC core.  So
that has to be taken into consideration.

					Regards,
					Tim

+--------------------------------+-------------------------------------+
| R. Timothy Edwards (Tim)       | email: tim@opencircuitdesign.com    |
| Open Circuit Design            | web:   http://opencircuitdesign.com |
| 19601 Jerusalem Road           | phone: (240) 489-3255               |
| Poolesville, MD 20837          | cell:  (408) 828-8212               |
+--------------------------------+-------------------------------------+

**Comment by hyf6661669** [comment]
@RTimothyEdwards 
OK, thanks!
